solving tasks with arrays.
Arahiz/ru-study-ruby pull request #1
Opened 2022-09-29 03:05 UTC by Arahiz

the file .rubocop.yml has been edited in order to eliminate error 'Carriage return character detected'

2022-09-29 19:21 UTC, NickelGit requested changes

2022-09-29 19:21 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        end
Вынеси пжлст поиск максимума в отдельный метод. Т.к. поиск максимума является самостоятельной операцией которая с большой долей вероятности может быть переиспользована в дальнейшем.

2022-09-29 19:21 UTC, NickelGit commented on test/exercise/arrays/solution.rb
>          array
перепиши пжлст с использованием функции `.map` и тернарной операции 
https://www.rubyguides.com/2018/10/ruby-map-method/

https://www.rubyguides.com/2019/10/ruby-ternary-operator/

2022-09-29 19:21 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        search(array[0..mid_position - 1], query)
давай попробуем вместо создания новых подмассивов просто смещать границы поиска внутри существующего массива и в конце рекурсивно вызывать наш метод каждый раз смещая границы поиска в нужную сторону.
Для первого вызова стоит использовать для границ поиска аргументы со значениями по умолчанию
https://medium.com/@sologoubalex/parameters-with-default-values-in-ruby-74cd0e830681

2022-09-29 23:43 UTC, Arahiz commented on test/exercise/arrays/solution.rb
> +        end
Метод  max должен быть внутри метода replace?

2022-09-30 05:49 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        end
метод max должен быть отдельным методом. Не нужно создавать метод внутри метода.

2022-09-30 05:54 UTC, Arahiz commented on test/exercise/arrays/solution.rb
> +        end
Done

2022-09-30 05:54 UTC, Arahiz commented on test/exercise/arrays/solution.rb
>          array
Done

2022-09-30 05:54 UTC, Arahiz commented on test/exercise/arrays/solution.rb
> +        search(array[0..mid_position - 1], query)
Done

2022-09-30 07:03 UTC, NickelGit requested changes

2022-09-30 07:03 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +          right = array.length
давай ассайнить это прямо на уровне аргументов, вот так
`search(array, query, left = 0, right = array.length - 1)`

2022-09-30 07:03 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        unless left
давай добавим сюда guard clause который будет проверять что в границах поиска еще есть что искать. (т.е. что наша левая граница не больше правой, проверка которая сейчас у тебя в 24й строке)
 А так же бинарный поиск возможен только в отсортированном массиве, поэтому мы точно знаем что слева всегда будет наименьшее значение, а справа наибольшее.
добавь пжлст проверку находится ли вообще элемент который мы ищем в границах нашего поиска.

2022-09-30 07:03 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        search(array, query, mid_position + 1, right)
перепиши пжлст это в виде тернарной операции.
для тернарной операции `return` здесь будет не нужен т.к. это будет последней строкой в методе, и нам вернется результат ее работы.

2022-09-30 07:03 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        return -1 if left == right
для облегчения чтения после `return` принято добавлять пустую строку.

2022-09-30 07:34 UTC, Arahiz commented on test/exercise/arrays/solution.rb
> +        search(array, query, mid_position + 1, right)
Линтер ругается и переправляет на if-else

2022-09-30 07:38 UTC, Arahiz commented on test/exercise/arrays/solution.rb
> +        search(array, query, mid_position + 1, right)
Отправляю с вариантом от линтера

2022-09-30 07:42 UTC, Arahiz commented on test/exercise/arrays/solution.rb
> +        return -1 if left == right
Done

2022-09-30 07:46 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        search(array, query, mid_position + 1, right)
обычно литер исправляет только вложенную тернарную операцию. Пришли пжлст в комментарии как ты пишешь до того как литер исправляет.

2022-09-30 07:48 UTC, Arahiz commented on test/exercise/arrays/solution.rb
> +        unless left
я правильно понимаю, что проверка типа if elem > array[-1] && elem < array[0]

2022-09-30 07:50 UTC, Arahiz commented on test/exercise/arrays/solution.rb
> +          right = array.length
я так изначально думал, но почему-то решил, что доступа к array не будет.
Хорошо

2022-09-30 07:50 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        unless left
почти, у нас же не всегда будет 0 и -1 т.к. мы границы поиска смещаем.
Должно быть что то типа
`if query > array[right] && query < array[left]`

2022-09-30 08:06 UTC, Arahiz commented on test/exercise/arrays/solution.rb
> +        search(array, query, mid_position + 1, right)
array[mid_position] > query ? search(array, query, left, mid_position - 1) :
search(array, query, mid_position + 1, right)

2022-09-30 08:11 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        search(array, query, mid_position + 1, right)
В файле `search(array, query, mid_position + 1, right)` так же на следующей строке? или все написано на одной строке?

2022-09-30 08:13 UTC, Arahiz commented on test/exercise/arrays/solution.rb
> +        search(array, query, mid_position + 1, right)
на двух строках

2022-09-30 08:14 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        search(array, query, mid_position + 1, right)
тогда это подпадает вот под это правило https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/MultilineTernaryOperator


Попробуй написать в одну строку

2022-09-30 08:15 UTC, Arahiz commented on test/exercise/arrays/solution.rb
> +        unless left
Done

2022-09-30 08:34 UTC, Arahiz commented on test/exercise/arrays/solution.rb
> +        search(array, query, mid_position + 1, right)
Done

2022-09-30 09:27 UTC, NickelGit approved these changes

2022-09-30 09:54 UTC, merged