fp tasks solving
Arahiz/ru-study-ruby pull request #2
Opened 2022-10-01 04:31 UTC by Arahiz

2022-10-01 18:35 UTC, greybutton requested changes

2022-10-01 18:35 UTC, greybutton commented on test/exercise/fp/solution.rb
> +        rating_array.reduce(0, :+) / rating_array.map { |rate| rate.positive? ? 1 : 0 }.reduce(0, :+)
добавим переменных чтобы код читабельнее стал?

2022-10-02 03:58 UTC, Arahiz commented on test/exercise/fp/solution.rb
> +        rating_array.reduce(0, :+) / rating_array.map { |rate| rate.positive? ? 1 : 0 }.reduce(0, :+)
Done

2022-10-02 10:41 UTC, greybutton approved these changes

2022-10-02 12:25 UTC, merged